import { defineType, defineField, defineArrayMember } from "sanity";

export default defineType({
  name: "caseStudy",
  title: "Case Study",
  type: "document",
  groups: [
    { name: "core", title: "Core Info" },
    { name: "content", title: "Content" },
    { name: "media", title: "Media" },
    { name: "seo", title: "SEO & Metadata" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "core",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "core",
      options: { source: "title" },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "clientName",
      title: "Client Name",
      type: "string",
      group: "core",
    }),
    defineField({
      name: "clientIndustry",
      title: "Client Industry",
      type: "string",
      group: "core",
    }),
    defineField({
      name: "role",
      title: "Your Role",
      type: "string",
      group: "core",
      description: 'e.g. "Lead Developer + Marketing"',
    }),
    defineField({
      name: "duration",
      title: "Project Duration",
      type: "string",
      group: "core",
    }),
    defineField({
      name: "liveUrl",
      title: "Live Site URL",
      type: "url",
      group: "core",
    }),
    defineField({
      name: "services",
      title: "Services Provided",
      type: "array",
      group: "core",
      of: [defineArrayMember({ type: "string" })],
      options: {
        list: [
          { title: "Web Development", value: "web-development" },
          { title: "Brand Strategy", value: "brand-strategy" },
          { title: "Growth Marketing", value: "growth-marketing" },
          { title: "Paid Media", value: "paid-media" },
          { title: "SEO & AEO", value: "seo-aeo" },
          { title: "Content Strategy", value: "content-strategy" },
          { title: "CMS Architecture", value: "cms-architecture" },
          { title: "Product Strategy", value: "product-strategy" },
          { title: "Email Marketing", value: "email-marketing" },
          { title: "Analytics Setup", value: "analytics-setup" },
        ],
      },
    }),
    defineField({
      name: "beforeState",
      title: "Before State (Card Preview)",
      type: "text",
      rows: 2,
      group: "core",
    }),
    defineField({
      name: "heroImage",
      title: "Hero Image",
      type: "image",
      group: "media",
      options: { hotspot: true },
    }),
    defineField({
      name: "heroVideo",
      title: "Hero Video",
      type: "file",
      group: "media",
      options: { accept: "video/*" },
      description: "Upload a video file for the case study hero. Falls back to the hero image if empty.",
    }),
    defineField({
      name: "gallery",
      title: "Project Gallery",
      type: "array",
      group: "media",
      of: [defineArrayMember({ type: "image", options: { hotspot: true } })],
      description: "Multiple images displayed as a carousel on the case study page. Add screenshots, wireframes, before/after comparisons.",
    }),
    defineField({
      name: "situation",
      title: "Situation",
      type: "array",
      group: "content",
      of: [defineArrayMember({ type: "block" })],
    }),
    defineField({
      name: "approach",
      title: "Approach",
      type: "array",
      group: "content",
      of: [defineArrayMember({ type: "block" })],
    }),
    defineField({
      name: "buildSection",
      title: "Build Section",
      type: "array",
      group: "content",
      of: [
        defineArrayMember({ type: "block" }),
        defineArrayMember({
          type: "image",
          options: { hotspot: true },
        }),
      ],
    }),
    defineField({
      name: "result",
      title: "Result",
      type: "array",
      group: "content",
      of: [defineArrayMember({ type: "block" })],
    }),
    defineField({
      name: "metrics",
      title: "Metrics",
      type: "array",
      group: "content",
      of: [
        defineArrayMember({
          type: "object",
          fields: [
            defineField({
              name: "label",
              title: "Label",
              type: "string",
            }),
            defineField({
              name: "value",
              title: "Value",
              type: "string",
            }),
          ],
        }),
      ],
    }),
    defineField({
      name: "tags",
      title: "Tags",
      type: "array",
      group: "core",
      of: [defineArrayMember({ type: "string" })],
      description: "Displayed as pills on the case study hero, e.g. SEO, PPC, React",
    }),
    defineField({
      name: "techStack",
      title: "Tech Stack",
      type: "array",
      group: "core",
      of: [
        defineArrayMember({
          type: "reference",
          to: [{ type: "toolRegistry" }],
        }),
      ],
    }),
    defineField({
      name: "testimonial",
      title: "Testimonial",
      type: "reference",
      group: "content",
      to: [{ type: "testimonial" }],
    }),
    defineField({
      name: "nextCaseStudy",
      title: "Next Case Study",
      type: "reference",
      group: "core",
      to: [{ type: "caseStudy" }],
    }),
    defineField({
      name: "featured",
      title: "Featured",
      type: "boolean",
      group: "core",
    }),
    defineField({
      name: "publishedAt",
      title: "Published At",
      type: "datetime",
      group: "core",
    }),
    defineField({
      name: "seoTitle",
      title: "SEO Title",
      type: "string",
      group: "seo",
    }),
    defineField({
      name: "seoDescription",
      title: "SEO Description",
      type: "text",
      rows: 3,
      group: "seo",
    }),
    defineField({
      name: "ogImage",
      title: "Social Share Image",
      type: "image",
      group: "seo",
    }),
  ],
  preview: {
    select: {
      title: "title",
      client: "clientName",
      subtitle: "clientIndustry",
      media: "heroImage",
    },
    prepare({ title, client, subtitle, media }) {
      return {
        title: title || "Untitled",
        subtitle: client ? `${client} — ${subtitle || ""}` : subtitle,
        media,
      };
    },
  },
});
